### ISSUE TITLE
OptimizerGlobalTest#testGlobalTooMuchVMs

### ISSUE THREAD

**Issue by fhermeni** [Plug4Green/Plug4Green#12]
Expected 4 moves, got 12.
Choco proved the solution optimality. This means the power model does not take effectively into account the impact of migrations ?

**Comment by cdupont** [comment]
I have:
move VM id120000 from id100000 to id200000
move VM id120001 from id100000 to id300000
move VM id120003 from id100000 to id300000
move VM id120002 from id100000 to id300000
move VM id220003 from id100000 to id200000
move VM id320000 from id300000 to id200000
move VM id220000 from id100000 to id200000
move VM id220001 from id100000 to id300000
move VM id220002 from id100000 to id200000
move VM id320002 from id300000 to id200000
move VM id320001 from id300000 to id200000
move VM id320003 from id300000 to id200000

There is two problems:
- id100000 gets emptied of its 8 VMs in favor of id200000, so VM movement cost seems not be taken into account,
- The overbooking factor was set at 1, servers have 4 cores so 8 VMs on id200000 is too much.

**Comment by fhermeni** [comment]
- There is no overbook constraint in the resulting BtrPlace model. So indeed a factor of 1 is assumed
- There is no notion of cores also. Only views "CPU", and "RAM". For CPU it denotes their consumption in terms of mips or sth. similar ?
- Nodes provide 400 CPU unit each, VM consume 50 each. Nothing is wrong on my side yet

**Comment by cdupont** [comment]
> There is no overbook constraint in the resulting BtrPlace model. So indeed a factor of 1 is assumed
Right
> There is no notion of cores also. Only views "CPU", and "RAM". For CPU it denotes their consumption in terms of mips or sth. similar ?
CPU view corresponds to the % of cores available. 2 CPU with 4 cores each = 800%.

> Nodes provide 400 CPU unit each, VM consume 50 each. Nothing is wrong on my side yet
That's right, I fixed the test so that VMs consumption is 100%.
Now the test doesn't seem to find a solution (BtrPlace model seem to be correct).

**Comment by fhermeni** [comment]
```
After 2669ms of search (terminated): 34649 opened search node(s), 69299 backtrack(s), 0 solution(s).
```
BtrPlace proved there is no solution. So the CSP model (btrPlace or P4G side) is incorrect if you expected one.

**Comment by cdupont** [comment]
What does that mean there is no solution? There is not enough space in the servers to host the VMs?

**Comment by fhermeni** [comment]
It means no variable assignment can lead to the satisfaction of all the constraints. You find a solution according to the constraints you have in mind. This means the model you have in mind differs from the one that is implemented. Remove some parts of the model to isolate the faults. The power model for example.

**Comment by fhermeni** [comment]
Removing the power stuff do not change the issue.
Going down to 3 vms per server lead to a solution.
Possibly a bug inside BtrPlace

**Comment by fhermeni** [comment]
Gotcha 

The problem is the initial model is not viable. It currently states node0 is overloaded. In reality, no server can run at 200%. So the initial model should be revised to be viable while constraints state the resource demand for the VMs.

**Comment by cdupont** [comment]
What is the constraint that should be put? Anyway I will probably close the case and put @Ignore on the test because the test not relevant any more.

**Comment by fhermeni** [comment]
Preserve is the constraint to use to ask for resources
