### ISSUE TITLE
OptimizerAllocationTest#testGlobalOneVMperServerVMNoLoad: reveal bad model

### ISSUE THREAD

**Issue by fhermeni** [Plug4Green/Plug4Green#15]
I reduced the test to 5 nodes (see a2cbdfb196bdb58f14d80f0e91da6021102007a4):

```
5 node(s); 5 VM(s); 0 constraint(s); optimize; timeout: 5s
Building duration: 355ms (core-RP) + 15ms (specialization)
After 1332ms of search (terminated): 32194 opened search node(s), 64387 backtrack(s), 1 solution(s):
	1) at 1330ms: 32194 node(s), 64341 backtrack(s), objective: 50
```
The solver proved the optimality of the solution but the resulting plan do not consolidate at all.
There might be sth. wrong inside the power model.

**Comment by cdupont** [comment]
If I put the VM CPU consumption to 1%, it works, but with 0% it doesn't.
So it might be a problem in BtrPlace.
Anyway I fixed the test (with 1%) so it works now :)

**Comment by fhermeni** [comment]
I want to check for a bug inside BtrPlace. How to set consumption to 0% ?

**Comment by cdupont** [comment]
Change 
optimizer.getVmTypes().getVMType().get(0).getExpectedLoad().setVCpuLoad(new CpuUsageType(1));
to 
optimizer.getVmTypes().getVMType().get(0).getExpectedLoad().setVCpuLoad(new CpuUsageType(0));
in the test.

**Comment by fhermeni** [comment]
Depending on the power model.
If a VM consumes 0, maybe the model computes it is cheaper to let the VM on the node rather than migrating it (costly in W) and shutting the node down.
How do you model the cost of turning a node off in terms of Watt. In practice the cost is the Watts during the plan + the watt up to the next call

**Comment by cdupont** [comment]
In the tests the power of a server is 10W, power of a VM is 1W, and there is a penalty of 1KJ for migrating a VM, and 1KJ for changing state of a server. 
Everything is that converted in KJ, because what we try to minimize is the energy spent by the data centre between 2 reconfiguration (1000 seconds) including powers of VMs, servers and moves/on/off penalties.
