### ISSUE TITLE
Add a main

### ISSUE THREAD

**Issue by cdupont** [Plug4Green/Plug4Green#19]
add a main in f4g.pluginCore.core.Main.java, to allow P4G to run standalone.
It should allow to listen to northbound interfaces, and initialize connector with OpenStack.

**Comment by santuari** [comment]
As suggested by cdupont, we can initialize it the same way, but in a standalone fashion: https://github.com/Plug4Green/Plug4Green/blob/antbuild/InitServlet/src/org/f4g/launcher/InitServlet.java

**Comment by cdupont** [comment]
Startup command is:

mvn exec:java -Dexec.mainClass="f4g.pluginCore.core.Main" -Dexec.args="src/main/config/pluginCore/f4gconfig.properties"

**Comment by santuari** [comment]
As suggested by cdupont, I create a new module that loads the communicators and the core. The Main core (f4g.pluginCore.core.Main) must be changed.
