### ISSUE TITLE
Create a Plug4Green demo

### ISSUE THREAD

**Issue by cdupont** [Plug4Green/Plug4Green#20]
A reproducible demo of Plug4Green + OS should be created.
The ideal would be to have a script installing everything on the client PC.
Otherwise a step-by-step description is also good.
IMO the demo should be stored in a separate GIT repo.

**Comment by santuari** [comment]
Is it a Plug4Green + CF or Plug4Green + OS?

**Comment by cdupont** [comment]
Done in P4GDemo sub package.
