### ISSUE TITLE
northbound interface

### ISSUE THREAD

**Issue by santuari** [Plug4Green/Plug4Green#8]
Discuss the new northbound interface used to comunicate with the EASC.

The northbound interface should provide:
- monitoring of VMs and Server (Cpu/Ram usage, Cpu/Ram capacity, Position)
- managing consolidation factor

**Comment by cdupont** [comment]
Fabien could you add your requirements regarding the communication with EASC-VM?

**Comment by cdupont** [comment]
Fabien any update?

**Comment by fhermeni** [comment]
I didn’t have time to go further however. 
In BtrPlace, the constraint preserve will do the job as we will play with the amount of resource (CPU ? MIPS ?) to allocate to the VMs.
So if you support that, that should be enough.

Fabien

**Comment by cdupont** [comment]
OK that sounds good. Should we have a REST interface or other?

**Comment by fhermeni** [comment]
I guess but please sth simple :D
There is already a native (and extensible) json interface for BtrPlace for example.
- https://github.com/btrplace/scheduler/wiki/JSON-Messages <https://github.com/btrplace/scheduler/wiki/JSON-Messages>
- http://www.btrplace.org/apidocs/index.html?org/btrplace/json/package-summary.html <http://www.btrplace.org/apidocs/index.html?org/btrplace/json/package-summary.html>

**Comment by cdupont** [comment]
Done d1230e41beaa0f707a45c1f7a2d6f1aef2bf20ea
